# Generated by Django 4.2.4 on 2023-08-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='age',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='father',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mother',
        ),
    ]
